name: Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        use: true
        driver: docker-container

    - name: Build/Publish Dev Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: urganot/papermerge-raspberry-auth-server:${{ github.ref_name }}
        file: docker/Dockerfile
        platforms: linux/amd64,linux/arm64

#    - name: Add description
#      uses: peter-evans/dockerhub-description@v3
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#        repository: papermerge/auth-server
#        readme-filepath: README.md
